apiVersion: v1
kind: Service
metadata:
  name: user-churn-predictor
  labels:
    app: user-churn-predictor
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9696
      protocol: TCP
      name: http
  selector:
    app: user-churn-predictor
