apiVersion: v1
kind: Service
metadata:
  name: trial-conversion-prediction
  namespace: default
  labels:
    app: trial-conversion-prediction
spec:
  type: ClusterIP
  selector:
    app: trial-conversion-prediction
  ports:
  - port: 80
    targetPort: 9696
    protocol: TCP
    name: http
